### ISSUE TITLE
Lua vs Haskell for Pandoc Custom Readers/Writers

### ISSUE THREAD

**Issue by raj-magesh** [Simre1/neorg-haskell-parser#11]
Hey, thanks for your work on the Neorg parser! I was skimming the Pandoc documentation when I noticed that custom readers/writers are typically written in Lua and not Haskell. Is there a specific reason you chose to implement the parser in Haskell?

**Comment by Simre1** [comment]
The only reason why the parser isn’t done in Lua is that I prefer to develop in Haskell.
If you want to implement a custom reader in Lua, then feel free to go ahead. My current Haskell parser is severely out of date with regards to the Neorg advancements, so an updated parser would definitely be needed.
