### ISSUE TITLE
Scope clarification: (pandoc AST -> norg) eventually?

### ISSUE THREAD

**Issue by d-r-a-b** [Simre1/neorg-haskell-parser#32]
Thanks for this cool project!

> It will be able to transform .norg files to the [pandoc](https://github.com/jgm/pandoc) AST and subsequently to the plethora of formats that pandoc supports.

This is great for reader capabilities and export from norg  to other formats. With the understanding that there is no commitment to follow through, or any commitment to any timeline, is there a plan for this project to extend to provide support for writer functionality (i.e. pandoc AST to norg)?

**Comment by Simre1** [comment]
For the basic features, this is not particularly hard. For more advanced features, it's not so easy:
- A few features are realized through setting the right classname to objects, which is difficult to find out about
- Many use Latex/HTML directly within Pandoc markdown
- Pandoc markdown may have features which are not supported by Norg

I personally will not try to implement this in the near future. However, I am also not against it and would accept MRs which implement this feature.
